### PR TITLE
Only install enum34 for python<3.4.

### PR DESCRIPTION
**Pull request by pvinci**

### CODE REVIEW

**Comment by Roguelazer** [comment]
What are your thoughts on the new pip way of specifying this as `enum34;python_version<="3.4"`?

**Comment by pvinci** [comment]
That works great in requirements.txt for pip.  There is an alternate syntax
for setup.py that is available with setuptools >=36.2, but how do you
guarantee the starting version of setuptools without requiring multiple
installation runs?

**Comment by pvinci** [comment]
Have you thought about how you'd like to resolve this?

As it stands, it breaks our py3 migration.

Traceback (most recent call last):
  File "/vpp/.tox/py36/lib/python3.6/warnings.py", line 505, in <module>
    _processoptions(sys.warnoptions)
  File "/vpp/.tox/py36/lib/python3.6/warnings.py", line 186, in _processoptions
    _setoption(arg)
  File "/vpp/.tox/py36/lib/python3.6/warnings.py", line 192, in _setoption
    import re
  File "/vpp/.tox/py36/lib/python3.6/re.py", line 122, in <module>
    import enum
ModuleNotFoundError: No module named 'enum'

**Comment by Roguelazer** [comment]
This is resolved in version 0.3.1. Sorry for the delay.

**Comment by pvinci** [comment]
Thank you so much!

**Pull request merged**
